name: todo
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  meta: ^1.2.4
  over_react: ^4.1.1
  react_material_ui:
    hosted:
      name: react_material_ui
      url: https://pub.workiva.org
    version: ^1.13.3
  redux: ">=4.0.0+3 <5.0.0"
  react: ^6.0.1

dev_dependencies:
  lints: ^1.0.0
  intl: ^0.15.8
  build_runner: ^1.7.0
  build_test: ^0.10.8
  build_web_compilers: ^2.4.0
  dart_dev: ^2.2.0
  dart_style: ^1.2.7
  over_react_test: ^2.5.1
  test: ^1.6.10
